# Generated by Django 5.2.17 on 2026-08-10 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('icon_name', models.CharField(blank=True, max_length=60)),
                ('tint', models.CharField(blank=True, max_length=20)),
                ('requires_system', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'exam categories',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('icon_name', models.CharField(blank=True, max_length=60)),
                ('tint', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(blank=True, choices=[('francophone', 'Francophone'), ('anglophone', 'Anglophone')], max_length=20, null=True)),
                ('name', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('mock_variant_label', models.CharField(blank=True, max_length=100)),
                ('tracks', models.JSONField(blank=True, default=list)),
                ('subject_language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2)),
                ('badge_tone', models.CharField(blank=True, default='neutral', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='papers.examcategory')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PaperSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system', models.CharField(blank=True, choices=[('francophone', 'Francophone'), ('anglophone', 'Anglophone')], max_length=20, null=True)),
                ('track', models.CharField(blank=True, max_length=60)),
                ('exam_board', models.CharField(blank=True, max_length=120)),
                ('year', models.PositiveIntegerField()),
                ('file_ref', models.CharField(max_length=500)),
                ('ocr_text', models.TextField(blank=True)),
                ('duplicate_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('mcq_section', models.JSONField(blank=True, null=True)),
                ('non_mcq_section', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('INSTRUCTOR_REQUEST_SENT', 'Instructor request sent'), ('INSTRUCTOR_ACCEPTED', 'Instructor accepted'), ('INSTRUCTOR_REJECTED', 'Instructor rejected'), ('AWAITING_MARKING_GUIDE', 'Awaiting marking guide'), ('GUIDE_SUBMITTED', 'Guide submitted'), ('MERGED', 'Merged'), ('PUBLISHED', 'Published'), ('UNASSIGNED_ADMIN_QUEUE', 'Unassigned — admin queue')], default='PENDING_REVIEW', max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='papers.examcategory')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='papers.examtype')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_submissions', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='papers.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='examtype',
            constraint=models.UniqueConstraint(fields=('category', 'system', 'name'), name='unique_exam_type_per_category_system'),
        ),
    ]
