# Generated by Django 5.2.17 on 2026-08-10 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paperviewlog_adwatchevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersubmission',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='papers.papersubmission'),
        ),
        migrations.AddField(
            model_name='papersubmission',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
    ]
