# Generated by Django 5.2.17 on 2026-08-10 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_papersubmission_duplicate_of_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQAnswerKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField()),
                ('authored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_mcq_keys', to=settings.AUTH_USER_MODEL)),
                ('paper_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mcq_answer_key', to='papers.papersubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublishedGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.JSONField()),
                ('published_at', models.DateTimeField()),
                ('paper_submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published_guide', to='papers.papersubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
