# Generated by Django 5.2.17 on 2026-08-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0005_mcqanswerkey_publishedguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersubmission',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='paper_submissions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='papersubmission',
            name='file_ref',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
