# Generated by Django 5.2.17 on 2026-08-15 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_papersubmission_uploaded_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('WRONG_ANSWERS', 'Wrong or missing answers'), ('POOR_QUALITY', 'Poor scan quality / unreadable'), ('WRONG_SUBJECT', 'Wrong subject or exam type'), ('DUPLICATE', 'Duplicate of another paper'), ('COPYRIGHT', 'Copyright concern'), ('OTHER', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_flags', to=settings.AUTH_USER_MODEL)),
                ('paper_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='papers.papersubmission')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('paper_submission', 'flagged_by'), name='unique_flag_per_user_per_paper')],
            },
        ),
    ]
