# Generated by Django 5.2.17 on 2026-08-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_paperflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersubmission',
            name='discipline',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='papersubmission',
            name='institution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='papersubmission',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
