# Generated by Django 5.2.17 on 2026-08-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0009_seed_report_exam_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='requires_payment_to_view',
            field=models.BooleanField(default=False),
        ),
    ]
