# Generated by Django 5.2.17 on 2026-08-23 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0011_gate_masters_and_phd_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtype',
            name='max_upload_mb',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
