# Generated by Django 5.2.17 on 2026-08-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0013_thesis_reports_larger_upload_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicReportSubmission',
            fields=[
            ],
            options={
                'verbose_name': 'Academic report',
                'verbose_name_plural': 'Academic reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('papers.papersubmission',),
        ),
    ]
