# Generated by Django 5.2.17 on 2026-08-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0014_academicreportsubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papersubmission',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('INSTRUCTOR_REQUEST_SENT', 'Instructor request sent'), ('INSTRUCTOR_ACCEPTED', 'Instructor accepted'), ('INSTRUCTOR_REJECTED', 'Instructor rejected'), ('AWAITING_MARKING_GUIDE', 'Awaiting marking guide'), ('GUIDE_SUBMITTED', 'Guide submitted'), ('MERGED', 'Merged'), ('PUBLISHED', 'Published'), ('UNASSIGNED_ADMIN_QUEUE', 'Unassigned: admin queue')], default='PENDING_REVIEW', max_length=32),
        ),
    ]
