# Generated by Django 5.2.17 on 2026-09-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0015_alter_papersubmission_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersubmission',
            name='dismissed_by_contributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='papersubmission',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='papersubmission',
            name='status',
            field=models.CharField(choices=[('PENDING_REVIEW', 'Pending review'), ('INSTRUCTOR_REQUEST_SENT', 'Instructor request sent'), ('INSTRUCTOR_ACCEPTED', 'Instructor accepted'), ('INSTRUCTOR_REJECTED', 'Instructor rejected'), ('AWAITING_MARKING_GUIDE', 'Awaiting marking guide'), ('GUIDE_SUBMITTED', 'Guide submitted'), ('MERGED', 'Merged'), ('PUBLISHED', 'Published'), ('UNASSIGNED_ADMIN_QUEUE', 'Unassigned: admin queue'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=32),
        ),
    ]
