# Generated by Django 5.2.17 on 2026-09-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0016_papersubmission_dismissed_by_contributor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="papersubmission",
            name="ocr_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="papersubmission",
            name="ocr_error",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="papersubmission",
            name="ocr_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("DONE", "Done"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
