# Generated by Django 5.2.17 on 2026-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("papers", "0018_backfill_ocr_status_for_already_ocrd_submissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="papersubmission",
            name="title",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
