# Generated by Django 6.1.1 on 2026-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("ONBOARDING", "Onboarding"),
                    ("SUBMISSION_STATUS", "Submission status changed"),
                    ("CREDIT_AWARDED", "Credit awarded"),
                    ("PAMPHLET_READY", "Pickup ticket ready"),
                    ("GENERIC", "Generic"),
                ],
                default="GENERIC",
                max_length=20,
            ),
        ),
    ]
