# Generated by Django 5.2.17 on 2026-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pamphletorder',
            name='payout_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pamphletorder',
            name='qr_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pamphletorder',
            name='qr_token',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pamphletorder',
            name='self_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
