# Generated by Django 5.2.17 on 2026-08-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlets', '0002_pamphletorder_payout_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pamphlet',
            options={'ordering': ['-is_featured', 'title']},
        ),
        migrations.AddField(
            model_name='pamphlet',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
