# Generated by Django 5.2.17 on 2026-08-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pamphlets", "0003_alter_pamphlet_options_pamphlet_is_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="pamphlet",
            name="academic_level",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="pamphlet",
            name="subject_title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
