# Generated by Django 5.2.17 on 2026-08-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pamphlets', '0003_alter_pamphlet_options_pamphlet_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pamphletorder',
            name='status',
            field=models.CharField(choices=[('PAID_HELD', 'Paid, held in escrow'), ('QR_ISSUED', 'QR issued'), ('RELEASED', 'Released to partner'), ('EXPIRED', 'Expired, flagged for admin review'), ('DISPUTED', 'Disputed')], default='PAID_HELD', max_length=12),
        ),
    ]
