# Generated by Django 6.1.1 on 2026-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pamphlets", "0005_pamphlet_academic_level_pamphlet_subject_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerbookshop",
            name="location",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="partnerbookshop",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
