# Generated by Django 6.1.1 on 2026-09-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pamphlets", "0006_partnerbookshop_location_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pamphlet",
            options={"ordering": ["-is_featured", "display_order", "title"]},
        ),
        migrations.AddField(
            model_name="pamphlet",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
