# Generated by Django 6.1.1 on 2026-09-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pamphlets", "0007_alter_pamphlet_options_pamphlet_display_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="pamphlet",
            name="cover_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="pamphlets/%Y/%m/"
            ),
        ),
    ]
