# Generated by Django 6.1.1 on 2026-09-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pamphlets", "0008_pamphlet_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="pamphletorder",
            name="delivery_address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="pamphletorder",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
