# Generated by Django 6.1.1 on 2026-09-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pamphlets", "0009_pamphletorder_delivery_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerbookshop",
            name="cni_number",
            field=models.CharField(
                default="", max_length=30, verbose_name="CNI number"
            ),
        ),
        migrations.AddField(
            model_name="partnerbookshop",
            name="full_name",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="partnerbookshop",
            name="momo_number",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="MTN MoMo number"
            ),
        ),
        migrations.AddField(
            model_name="partnerbookshop",
            name="nui_number",
            field=models.CharField(
                default="", max_length=30, verbose_name="NUI number"
            ),
        ),
        migrations.AddField(
            model_name="partnerbookshop",
            name="orange_money_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="Orange Money number",
            ),
        ),
        migrations.AlterField(
            model_name="partnerbookshop",
            name="contact_email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="partnerbookshop",
            name="location",
            field=models.CharField(max_length=255),
        ),
    ]
