# Generated by Django 6.1.1 on 2026-09-17 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "pamphlets",
            "0010_partnerbookshop_cni_number_partnerbookshop_full_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="RedeemVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[("EMAIL", "Email"), ("PHONE", "Phone (SMS)")],
                        max_length=10,
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=6)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redeem_verifications",
                        to="pamphlets.pamphletorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
