# Generated by Django 6.1.1 on 2026-09-17 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pamphlets", "0011_redeemverification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="redeemverification",
            name="issued_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="redeemverification",
            name="channel",
            field=models.CharField(
                choices=[
                    ("EMAIL", "Email"),
                    ("PHONE", "Phone (SMS)"),
                    ("SUPPORT", "Support override (Integration Ops)"),
                ],
                max_length=10,
            ),
        ),
    ]
