# Generated by Django 6.1.1 on 2026-09-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pamphlets", "0012_redeemverification_issued_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerbookshop",
            name="cni_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="partner_kyc/%Y/%m/",
                verbose_name="CNI document",
            ),
        ),
        migrations.AddField(
            model_name="partnerbookshop",
            name="nui_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="partner_kyc/%Y/%m/",
                verbose_name="NUI document",
            ),
        ),
    ]
