# Generated by Django 6.1.1 on 2026-09-18 10:01

import apps.papers.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pamphlets", "0013_partnerbookshop_cni_document_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partnerbookshop",
            name="cni_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="partner_kyc/%Y/%m/",
                validators=[apps.papers.validation.validate_document_file_content],
                verbose_name="CNI document",
            ),
        ),
        migrations.AlterField(
            model_name="partnerbookshop",
            name="nui_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="partner_kyc/%Y/%m/",
                validators=[apps.papers.validation.validate_document_file_content],
                verbose_name="NUI document",
            ),
        ),
    ]
