# Generated by Django 5.2.17 on 2026-08-10 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('papers', '0005_mcqanswerkey_publishedguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfileCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('subjects', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner_id', models.CharField(max_length=100, unique=True)),
                ('hmac_secret', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor_id', models.CharField(db_index=True, max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('kyc_status', models.CharField(default='PENDING', max_length=30)),
                ('payout_method', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorCreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor_id', models.CharField(db_index=True, max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('paper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='papers.papersubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstructorMarkingGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor_id', models.CharField(db_index=True, max_length=100)),
                ('content', models.JSONField()),
                ('submitted_at', models.DateTimeField()),
                ('paper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_marking_guide', to='papers.papersubmission')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstructorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor_id', models.CharField(db_index=True, max_length=100)),
                ('sent_at', models.DateTimeField()),
                ('responds_by', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending response'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('TIMED_OUT', 'Timed out')], default='PENDING', max_length=10)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('guide_deadline', models.DateTimeField(blank=True, null=True)),
                ('day4_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('day6_reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_requests', to='papers.papersubmission')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'ACCEPTED'])), fields=('paper',), name='one_active_instructor_request_per_paper')],
            },
        ),
        migrations.CreateModel(
            name='InstructorSubjectQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor_id', models.CharField(db_index=True, max_length=100)),
                ('priority_order', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_queue', to='papers.subject')),
            ],
            options={
                'ordering': ['subject', 'priority_order'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'instructor_id'), name='unique_instructor_per_subject_queue')],
            },
        ),
    ]
