# Generated by Django 6.1.1 on 2026-09-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructormarkingguide",
            name="guide_file",
            field=models.FileField(
                blank=True, null=True, upload_to="marking_guides/%Y/%m/"
            ),
        ),
    ]
