# Generated by Django 6.1.1 on 2026-09-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("instructors", "0002_instructormarkingguide_guide_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructorprofilecache",
            name="qualified_categories",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
