# Generated by Django 5.2.17 on 2026-09-05 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=64)),
                ('kind', models.CharField(choices=[('summary', 'Summary')], max_length=32)),
                ('language', models.CharField(default='en', max_length=5)),
                ('prompt_version', models.PositiveSmallIntegerField()),
                ('source_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('body', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=64)),
                ('tokens_in', models.PositiveIntegerField(default=0)),
                ('tokens_out', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'kind'], name='ai_generate_status_3c597e_idx')],
                'unique_together': {('content_type', 'object_id', 'kind', 'language', 'prompt_version')},
            },
        ),
    ]
