# Generated by Django 6.1.1 on 2026-09-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('sponsor_name', models.CharField(blank=True, max_length=100)),
                ('icon_name', models.CharField(blank=True, max_length=60)),
                ('cta_label', models.CharField(blank=True, max_length=60)),
                ('cta_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
