# Generated by Django 6.1.1 on 2026-09-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='promotions/%Y/%m/'),
        ),
    ]
