# Generated by Django 5.2.17 on 2026-08-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_seed_quizzes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['title'], 'verbose_name_plural': 'quizzes'},
        ),
    ]
