# Generated by Django 6.1.1 on 2026-09-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='xp_awarded',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
