# Generated by Django 5.2.17 on 2026-08-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_seed_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="academic_level",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="note",
            name="subject_title",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
