# Generated by Django 6.1.1 on 2026-09-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_backfill_subject_and_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="pdf_file",
            field=models.FileField(blank=True, null=True, upload_to="notes/%Y/%m/"),
        ),
    ]
