# Generated by Django 6.1.1 on 2026-09-18 10:01

import apps.papers.validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_note_pdf_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="pdf_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="notes/%Y/%m/",
                validators=[apps.papers.validation.validate_pdf_file_content],
            ),
        ),
    ]
