# Generated by Django 6.1.1 on 2026-09-28 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0006_alter_note_pdf_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["sort_order", "title"],
                "verbose_name": "summary note",
                "verbose_name_plural": "summary notes",
            },
        ),
        migrations.AddField(
            model_name="note",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"groups__name": "Support"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_notes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="body",
            field=models.TextField(blank=True),
        ),
    ]
