# Generated by Django 5.2.17 on 2026-08-15 02:09

import uuid

import apps.accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_referral_codes(apps_registry, schema_editor):
    # A plain AddField with a callable default bakes ONE computed value into
    # the ALTER TABLE's DEFAULT clause, applied identically to every existing
    # row — a guaranteed unique-constraint violation for any table with more
    # than one row. Backfilling per-row here (before the AlterField below
    # adds the unique constraint) gives every existing user a real distinct
    # code instead. Inlined rather than calling the app's
    # generate_referral_code so this migration stays correct even if that
    # function's implementation changes later.
    User = apps_registry.get_model('accounts', 'User')
    for user in User.objects.all():
        user.referral_code = uuid.uuid4().hex[:8].upper()
        user.save(update_fields=['referral_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_bonus_awarded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=apps.accounts.models.generate_referral_code, max_length=10, null=True),
        ),
        migrations.RunPython(backfill_referral_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(default=apps.accounts.models.generate_referral_code, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
