# Generated by Django 6.1.1 on 2026-09-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_reviewer_notes_pamphlets_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bonus_offline_slot_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
