# Generated by Django 6.1.1 on 2026-09-22 11:37

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_integration_ops_redeemverification_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffAccount",
            fields=[],
            options={
                "verbose_name": "Staff account",
                "verbose_name_plural": "Staff accounts",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("accounts.user",),
            managers=[
                ("objects", apps.accounts.models.UserManager()),
            ],
        ),
    ]
