# Generated by Django 5.2.17 on 2026-08-27 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0015_alter_papersubmission_status'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='purpose',
            field=models.CharField(choices=[('SUBSCRIPTION', 'Pro subscription'), ('PAPER_UNLOCK', 'Marking guide unlock'), ('PAPER_DOWNLOAD', 'Exam paper download unlock'), ('PAMPHLET_ORDER', 'Pamphlet order')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaperDownloadUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paid', models.PositiveIntegerField()),
                ('paper_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_unlocks', to='papers.papersubmission')),
                ('payment_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paper_download_unlocks', to='payments.paymenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paper_download_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'paper_submission'), name='unique_download_unlock_per_user_per_paper')],
            },
        ),
    ]
