# Generated by Django 5.2.17 on 2026-08-14 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rename_open_to_new(apps, schema_editor):
    # FlagStatus.OPEN was renamed to FlagStatus.NEW (spec §2.1's 3-state
    # New -> In Progress -> Resolved) — existing stored rows still say
    # 'OPEN' and need updating, not just the choices metadata.
    AdminFlagQueue = apps.get_model('admin_queue', 'AdminFlagQueue')
    AdminFlagQueue.objects.filter(status='OPEN').update(status='NEW')


def rename_new_to_open(apps, schema_editor):
    AdminFlagQueue = apps.get_model('admin_queue', 'AdminFlagQueue')
    AdminFlagQueue.objects.filter(status='NEW').update(status='OPEN')


class Migration(migrations.Migration):

    dependencies = [
        ('admin_queue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adminflagqueue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminflagqueue',
            name='category',
            field=models.CharField(choices=[('PAPER_VERIFICATION', 'New submission needs verification'), ('UNASSIGNED_PAPER', 'No instructor accepted'), ('GUIDE_REVIEW', 'Marking guide returned — needs review/merge'), ('PAMPHLET_DISPUTE', 'Pamphlet handover dispute'), ('PAMPHLET_EXPIRED', 'Pamphlet ticket expired unredeemed'), ('WITHDRAWAL_APPROVAL', 'Instructor withdrawal needs KYC/payout approval'), ('WEBHOOK_ANOMALY', 'Instructor webhook contradicted local state'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='adminflagqueue',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='NEW', max_length=12),
        ),
        migrations.RunPython(rename_open_to_new, rename_new_to_open),
    ]
