# Generated by Django 5.2.17 on 2026-08-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_queue', '0003_alter_adminflagqueue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminflagqueue',
            name='category',
            field=models.CharField(choices=[('PAPER_VERIFICATION', 'New submission needs verification'), ('PAPER_REPORTED', 'Paper reported by a user'), ('UNASSIGNED_PAPER', 'No instructor accepted'), ('GUIDE_REVIEW', 'Marking guide returned, needs review/merge'), ('PAMPHLET_DISPUTE', 'Pamphlet handover dispute'), ('PAMPHLET_EXPIRED', 'Pamphlet ticket expired unredeemed'), ('WITHDRAWAL_APPROVAL', 'Instructor withdrawal needs KYC/payout approval'), ('WEBHOOK_ANOMALY', 'Instructor webhook contradicted local state'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
