# Generated by Django 5.2.17 on 2026-08-10 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
        ('papers', '0004_papersubmission_duplicate_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorBonusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LevelComplexityMultiplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.CharField(choices=[('BASIC', 'Primary / basic secondary'), ('O_LEVEL', 'O-Level / BEPC / Probatoire'), ('A_LEVEL', 'A-Level / Baccalauréat'), ('UNIVERSITY', 'University')], max_length=20, unique=True)),
                ('multiplier', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionTypeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_type', models.CharField(choices=[('SHORT_ANSWER', 'Short-answer / structured'), ('CALCULATION', 'Calculation / derivation'), ('ESSAY', 'Essay / long-form'), ('MCQ', 'Multiple choice (never instructor-priced)')], max_length=20, unique=True)),
                ('base_rate_xaf', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RedeemCodeTierConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_submissions', models.PositiveIntegerField(unique=True)),
                ('value_percent', models.PositiveSmallIntegerField()),
                ('expiry_days', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['min_submissions'],
            },
        ),
        migrations.CreateModel(
            name='SubjectDemandFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factor', models.DecimalField(decimal_places=2, default=1, max_digits=4)),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demand_factor', to='papers.subject')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
