# Generated by Django 5.2.17 on 2026-08-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0003_seed_credit_rules_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCeilingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_credit_per_paper_xaf', models.PositiveIntegerField(default=5000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
