# Generated by Django 5.2.17 on 2026-08-15 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0004_creditceilingconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralBonusConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(default=200)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
