# Generated by Django 6.1.1 on 2026-09-28 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("credits", "0006_alter_creditledgerentry_options"),
        ("papers", "0020_fix_em_dash_in_category_subtitles"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedeemCodeContribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="credits.redeemcode",
                    ),
                ),
                (
                    "paper_submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redeem_code_contribution",
                        to="papers.papersubmission",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
